site_name: hackerspace nijmegen wiki
docs_dir: docs
site_description: Public Wiki For The Hackerspace Nijmegen
copyright: 2018 (c) Hackerspace Nijmegen, CC-By-Sa 3.5
theme: alabaster
theme_dir: custom_theme
site_dir: /var/www/wiki
markdown_extensions:
  - wikilinks
  - codehilite
  - toc(permalink=true)
extra:
   #logo: img/logo256x128.png
   #logo_name: "wiki"
  include_toc: yes
  extra_nav_links:
     Git: https://github.com/hackerspace-nijmegen
     Twitter: https://twitter.com/Hackerspace024

pages:
  - Home: 'index.md'
  - About: 'about.md'
