site_name: Hackerspace Nijmegen Wiki
docs_dir: docs
site_description: Wiki For The Hackerspace Nijmegen
copyright: 2018 (c) Hackerspace Nijmegen, CC-By-Sa 3.5
theme: alabaster
theme_dir: custom_theme
site_dir: /var/www/wiki
markdown_extensions:
  - wikilinks
  - codehilite
  - toc(permalink=true)
extra:
  logo: img/logo.jpg
  logo_name: "hackerspace nijmegen"
  include_toc: yes
  extra_nav_links:
     Github: https://github.com/hackerspace-nijmegen
     Twitter: https://twitter.com/Hackerspace024

pages:
  - Home: 'index.md'
  - About: 'about.md'
  - CFP: 'callforparticipation.md'
  - 'Last Minutes': 'minutes/2018-1.md'
  - 'Space Opening': 'spaceopening.md'

